import { Nav } from '@/components/Nav'
import { Footer } from '@/components/Footer'

export const metadata = { title: 'Terms of Service — TradeQuote' }

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-neutral-950">
      <Nav />
      <main className="max-w-3xl mx-auto px-4 py-12 prose prose-invert prose-neutral">
        <h1 className="font-display font-bold text-3xl uppercase tracking-tight mb-2">Terms of Service</h1>
        <p className="text-neutral-500 text-sm mb-8">Last updated: March 2026</p>

        <section className="space-y-6 text-neutral-300 text-sm leading-relaxed">

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">1. Service Description</h2>
            <p>TradeQuote is an AI-powered quoting tool for tradespeople (plumbers, electricians, HVAC technicians, and similar trades). The service allows subscribers to generate, manage, and send professional PDF quotes to their customers via a web application and WhatsApp integration.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">2. Eligibility</h2>
            <p>You must be at least 18 years old and operating a legitimate trade business to use TradeQuote. By creating an account you confirm that the information you provide is accurate and that you are authorised to enter into this agreement.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">3. Free Trial</h2>
            <p>New accounts receive a 7-day free trial with access to all features, up to a maximum of 10 quotes. No payment details are required to start a trial. At the end of the trial period, continued access requires a paid subscription.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">4. Subscription &amp; Billing</h2>
            <p>Paid subscriptions are billed monthly in advance through Paddle, our payment processor. You authorise us to charge your chosen payment method on a recurring basis. Prices are shown in USD and may be subject to local taxes. We reserve the right to change pricing with 30 days&apos; notice.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">5. Cancellation</h2>
            <p>You may cancel your subscription at any time through the billing portal. Cancellation takes effect at the end of the current billing period. You retain access to the service until that date. We do not provide refunds for unused portions of a billing period.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">6. User Responsibilities</h2>
            <p>You are solely responsible for the accuracy of quotes you generate and send to your customers. You agree not to use the service for any unlawful purpose, to impersonate others, or to distribute spam. You must keep your account credentials secure and notify us immediately of any unauthorised access.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">7. No Guarantee of Quote Accuracy</h2>
            <p>TradeQuote uses AI to assist in building quotes based on information you provide. We do not guarantee that prices, line items, or totals generated by the AI are accurate, complete, or suitable for any particular job. You are responsible for reviewing all quotes before sending them to customers. TradeQuote accepts no liability for financial loss arising from inaccurate quotes.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">8. Intellectual Property</h2>
            <p>All content, software, and technology comprising TradeQuote is owned by or licensed to us. You retain ownership of all quote data, customer information, and business content you upload. You grant us a limited licence to store and process that data solely to provide the service.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, TradeQuote and its operators are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability for any claim shall not exceed the amount you paid us in the 30 days preceding the claim.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">10. Changes to These Terms</h2>
            <p>We may update these terms from time to time. We will notify you by email at least 14 days before material changes take effect. Continued use of the service after that date constitutes acceptance of the revised terms.</p>
          </div>

          <div>
            <h2 className="text-neutral-100 font-bold text-lg uppercase tracking-wide mb-2">11. Contact</h2>
            <p>For questions about these terms, contact us at support@tradequote.app.</p>
          </div>

        </section>
      </main>
      <Footer />
    </div>
  )
}
